//! SQL over the binary protocol: `box.execute` and `box.prepare`, from Rust.
//!
//! Tarantool's SQL runs on the same spaces as the `NoSQL` API: a
//! `CREATE TABLE` is a space with a format — so the two mix freely. Statements that
//! return rows go through [`Client::query`], everything else through
//! [`Client::execute`]; both have twins on [`Stream`] for use inside a
//! transaction, and [`Client::prepare`] parses a statement once to run it
//! many times.
//!
//! Rows decode through `serde` exactly like tuples: into a `struct`, a
//! tuple, or a [`Value`]. Parameters are an [`Args`] list, in
//! which a plain value fills the next `?` and a [`Named`] fills a `:name`.
//!
//! [`Value`]: crate::Value
//! [`Client::query`]: crate::Client::query
//! [`Client::execute`]: crate::Client::execute
//! [`Client::prepare`]: crate::Client::prepare
//! [`Stream`]: crate::Stream

use std::collections::BTreeMap;
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};

use bytes::Bytes;
use rmpv::Value;
use serde::de::DeserializeOwned;
use serde::ser::{Serialize, SerializeMap, Serializer};

use crate::codec::{Request, Response};
use crate::connection::Handle;
use crate::error::{Error, ErrorCode, Result};
use crate::iproto::{key, request, sql};
use crate::tuple::{Args, encode_array};

/// A named parameter: `Named("min", 18)` fills `:min` in the statement.
///
/// Positional `?` parameters take plain values; the two kinds can be mixed
/// in one list, and named ones may appear in any order. A name without a
/// `:`, `@` or `$` prefix gets a colon.
///
/// ```
/// use tarant::sql::Named;
///
/// # async fn demo(client: tarant::Client) -> tarant::Result<()> {
/// let admins: Vec<(u64, String)> = client
///     .query(
///         "SELECT id, name FROM users WHERE age >= :min AND role = ?",
///         (Named("min", 18), "admin"),
///     )
///     .await?
///     .rows;
/// # Ok(()) }
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Named<'a, T>(pub &'a str, pub T);

impl<T: Serialize> Serialize for Named<'_, T> {
    fn serialize<S: Serializer>(&self, s: S) -> std::result::Result<S::Ok, S::Error> {
        let mut map = s.serialize_map(Some(1))?;
        if self.0.starts_with([':', '@', '$']) {
            map.serialize_entry(self.0, &self.1)?;
        } else {
            map.serialize_entry(&format!(":{}", self.0), &self.1)?;
        }
        map.end()
    }
}

/// One column of a result set, from `IPROTO_METADATA`.
///
/// `name` and `type_name` are always present. The rest arrive only when the
/// session setting `sql_full_metadata` is on.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
#[non_exhaustive]
pub struct Column {
    /// The column's name, or the expression's text for an unnamed one.
    pub name: String,
    /// The SQL type: `integer`, `string`, `boolean`, `double`, `decimal`, `uuid`, …
    pub type_name: String,
    /// The collation of a string column.
    pub collation: Option<String>,
    /// Whether the column may hold `NULL`.
    pub nullable: Option<bool>,
    /// Whether the column is `AUTOINCREMENT`.
    pub autoincrement: Option<bool>,
    /// The original expression under `SELECT`.
    pub span: Option<String>,
}

/// The result of a `SELECT`, `VALUES` or `PRAGMA`.
#[derive(Debug, Clone)]
pub struct Rows<T> {
    /// A description of each column, in row order.
    pub columns: Vec<Column>,
    /// The rows, each decoded as `T`.
    pub rows: Vec<T>,
}

/// What a statement that changes data reported.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
#[non_exhaustive]
pub struct Exec {
    /// Rows inserted, updated or deleted; `0` for statements that return rows.
    pub row_count: u64,
    /// Primary keys generated by an `INSERT` into an `AUTOINCREMENT` column.
    pub autoincrement_ids: Vec<u64>,
}

/// A statement the server parsed once, ready to run many times.
///
/// Comes from [`Client::prepare`](crate::Client::prepare). A prepared
/// statement belongs to the session that made it; if the connection is
/// re-established the statement is prepared again on its next use, without
/// the caller noticing. Dropping it releases the server-side statement.
pub struct Statement {
    handle: Handle,
    sql: String,
    id: AtomicU64,
    columns: Vec<Column>,
    parameters: Vec<Column>,
    parameter_count: u64,
    released: bool,
}

impl Statement {
    pub(crate) async fn prepare(handle: Handle, sql: String) -> Result<Self> {
        let response = send_prepare(&handle, &sql).await?;
        Ok(Self {
            columns: columns(response.metadata_bytes())?,
            parameters: columns(response.bind_metadata_bytes())?,
            parameter_count: response.bind_count().unwrap_or(0),
            id: AtomicU64::new(statement_id(&response)?),
            released: false,
            handle,
            sql,
        })
    }

    /// The statement text.
    pub fn sql(&self) -> &str {
        &self.sql
    }

    /// The columns a `query` will return; empty for statements without rows.
    pub fn columns(&self) -> &[Column] {
        &self.columns
    }

    /// The parameters the statement takes, as the server describes them.
    pub fn parameters(&self) -> &[Column] {
        &self.parameters
    }

    /// How many parameters the statement takes.
    pub fn parameter_count(&self) -> usize {
        usize::try_from(self.parameter_count).unwrap_or(usize::MAX)
    }

    /// Run the statement and decode its rows as `T`.
    pub async fn query<T: DeserializeOwned>(&self, params: impl Args) -> Result<Rows<T>> {
        rows(&self.run(None, params).await?)
    }

    /// Run the statement for its effect on the data.
    pub async fn execute(&self, params: impl Args) -> Result<Exec> {
        exec(&self.run(None, params).await?)
    }

    /// Release the server-side statement now rather than on drop.
    pub async fn unprepare(mut self) -> Result<()> {
        self.released = true;
        let sync = self.handle.next_sync();
        self.handle.request(sync, self.unprepare_packet(sync)).await.map(drop)
    }

    pub(crate) async fn run(&self, stream: Option<u64>, params: impl Args) -> Result<Response> {
        let bind = encode_array(&params)?;
        match self.send(stream, &bind).await {
            Err(Error::Server(err)) if err.code == ErrorCode::WRONG_QUERY_ID => {
                // The session that prepared this is gone: the connection was
                // re-established. Prepare again, then retry once.
                let fresh = send_prepare(&self.handle, &self.sql).await?;
                self.id.store(statement_id(&fresh)?, Ordering::Relaxed);
                self.send(stream, &bind).await
            }
            other => other,
        }
    }

    async fn send(&self, stream: Option<u64>, bind: &[u8]) -> Result<Response> {
        let sync = self.handle.next_sync();
        let packet = Request::new(request::EXECUTE, sync, stream)
            .uint(key::STMT_ID, self.id.load(Ordering::Relaxed))
            .raw(key::SQL_BIND, bind)
            .finish();
        self.handle.request(sync, packet).await
    }

    fn unprepare_packet(&self, sync: u64) -> Bytes {
        Request::new(request::PREPARE, sync, None)
            .uint(key::STMT_ID, self.id.load(Ordering::Relaxed))
            .finish()
    }
}

impl Drop for Statement {
    fn drop(&mut self) {
        if !self.released {
            // Best effort, like a rollback from Drop: nothing can be awaited here.
            self.handle.fire(self.unprepare_packet(self.handle.next_sync()));
        }
    }
}

impl fmt::Debug for Statement {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Statement")
            .field("sql", &self.sql)
            .field("parameters", &self.parameter_count)
            .finish_non_exhaustive()
    }
}

/// Run `sql` as text, optionally inside a stream.
pub(crate) async fn run_text(
    handle: &Handle,
    stream: Option<u64>,
    sql: &str,
    params: impl Args,
) -> Result<Response> {
    let sync = handle.next_sync();
    let packet = Request::new(request::EXECUTE, sync, stream)
        .str(key::SQL_TEXT, sql)
        .array(key::SQL_BIND, &params)?
        .finish();
    handle.request(sync, packet).await
}

async fn send_prepare(handle: &Handle, sql: &str) -> Result<Response> {
    let sync = handle.next_sync();
    let packet = Request::new(request::PREPARE, sync, None).str(key::SQL_TEXT, sql).finish();
    handle.request(sync, packet).await
}

fn statement_id(response: &Response) -> Result<u64> {
    response.stmt_id().ok_or_else(|| Error::protocol("PREPARE reply carries no statement id"))
}

/// The result set of `response`, or an error if it has none.
pub(crate) fn rows<T: DeserializeOwned>(response: &Response) -> Result<Rows<T>> {
    if !response.has_data() {
        return Err(Error::decode(NoResultSet));
    }
    Ok(Rows { columns: columns(response.metadata_bytes())?, rows: response.data()? })
}

/// The `IPROTO_SQL_INFO` of `response`; all zeros if it has none.
pub(crate) fn exec(response: &Response) -> Result<Exec> {
    let Some(bytes) = response.sql_info_bytes() else { return Ok(Exec::default()) };
    let info: BTreeMap<u8, Value> = rmp_serde::from_slice(bytes).map_err(Error::decode)?;
    let row_count = info.get(&sql::INFO_ROW_COUNT).and_then(Value::as_u64).unwrap_or(0);
    let autoincrement_ids = info
        .get(&sql::INFO_AUTOINCREMENT_IDS)
        .and_then(Value::as_array)
        .map(|ids| ids.iter().filter_map(Value::as_u64).collect())
        .unwrap_or_default();
    Ok(Exec { row_count, autoincrement_ids })
}

/// Decode an `IPROTO_METADATA` or `IPROTO_BIND_METADATA` array.
fn columns(bytes: Option<&[u8]>) -> Result<Vec<Column>> {
    let Some(bytes) = bytes else { return Ok(Vec::new()) };
    let entries: Vec<BTreeMap<u8, Value>> = rmp_serde::from_slice(bytes).map_err(Error::decode)?;
    let text = |entry: &BTreeMap<u8, Value>, k: u8| entry.get(&k)?.as_str().map(str::to_owned);
    let flag = |entry: &BTreeMap<u8, Value>, k: u8| entry.get(&k)?.as_bool();
    Ok(entries
        .iter()
        .map(|entry| Column {
            name: text(entry, sql::FIELD_NAME).unwrap_or_default(),
            type_name: text(entry, sql::FIELD_TYPE).unwrap_or_default(),
            collation: text(entry, sql::FIELD_COLL),
            nullable: flag(entry, sql::FIELD_IS_NULLABLE),
            autoincrement: flag(entry, sql::FIELD_IS_AUTOINCREMENT),
            span: text(entry, sql::FIELD_SPAN),
        })
        .collect())
}

#[derive(Debug)]
struct NoResultSet;

impl fmt::Display for NoResultSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "the statement returned no result set; use `execute` for statements that change data",
        )
    }
}

impl std::error::Error for NoResultSet {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn named_parameters_become_single_entry_maps() {
        let bytes = rmp_serde::to_vec(&Named("min", 18)).unwrap();
        let value = rmpv::decode::read_value(&mut &bytes[..]).unwrap();
        assert_eq!(value, Value::Map(vec![(Value::from(":min"), Value::from(18))]));
        let bytes = rmp_serde::to_vec(&Named("@x", "y")).unwrap();
        let value = rmpv::decode::read_value(&mut &bytes[..]).unwrap();
        assert_eq!(value, Value::Map(vec![(Value::from("@x"), Value::from("y"))]));
    }

    #[test]
    fn a_parameter_list_mixes_positional_and_named() {
        let bytes = encode_array(&(1u32, Named("name", "ann"), true)).unwrap();
        let value = rmpv::decode::read_value(&mut &bytes[..]).unwrap();
        assert_eq!(
            value,
            Value::Array(vec![
                Value::from(1),
                Value::Map(vec![(Value::from(":name"), Value::from("ann"))]),
                Value::from(true),
            ])
        );
    }
}
